version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - my-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=WorkoutUser
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
