global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs'
    static_configs:
      - targets: ['app:3000']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
